### ISSUE TITLE
Suggestion: Command line arguments

### ISSUE THREAD

**Issue by lpabon** [gaurav36/gluster_volfile_gen2.0#1]
Hi @gaurav36 , I also noticed that you may want to look at https://golang.org/pkg/flag/ for command line arguments.

Here is how I used it:
https://github.com/pblcache/pblcache/blob/master/apps/pblio/pblio.go#L58

**Comment by gaurav36** [comment]
hi @lpabon  thank you for this suggestion. Yes, flag will be good for CLI argument. I will use it in next patch set.
